### ISSUE TITLE
Transcript panel showing by default

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-video-standards-and-benefits#2]
Is this do-able?

Any reason not to do it?

An advantage is it makes the full subtitle list available (see https://github.com/w3c/wai-video-standards-and-benefits/issues/1) -- and then we can get rid of the instructions at https://www.w3.org/WAI/videos/standards-and-benefits.html#translations

**Comment by yatil** [comment]
Viewers who do not need the transcript panel might be distracted by the subtitle and we’d need instructions on how to hide it, negating the instructions (which we didn’t decide to put anywhere else). I’m pretty sure people with transcript needs are more likely to figure out where to open them out of habit while people who do not use transcripts might just say “this is weird accessibility stuff that distracts me from the video” and leave the page because they think it is mandatory to have it. People who have activated the transcript once have it open by default on new pages (cookie is set).

**Comment by yatil** [comment]
BTW: Quick skim looks like we **cannot** enable it by default: https://github.com/ableplayer/ableplayer

**Comment by slhenry** [comment]
Let's just close this issue then.
