### ISSUE TITLE
[fr] updates needed

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-video-standards-and-benefits#60]
* [x] updates in [changelog](https://www.w3.org/WAI/videos/standards-and-benefits/changelog/)
* [x] footer text needs translated (get the update from the changelog first ;-)
* [ ] [VTT](https://github.com/w3c/wai-video-standards-and-benefits/blob/master/content-images/wai-video-standards-and-benefits/W3C_INTRO_SFHI.fr.vtt) file and the [transcript table](https://www.w3.org/WAI/videos/standards-and-benefits/fr#transcript) need edited a bit so the text is the same

**Comment by notabene** [comment]
Done in https://github.com/notabene/wai-video-standards-and-benefits/tree/fr-translation-update

* Looked at [changelog](https://www.w3.org/WAI/videos/standards-and-benefits/changelog/)
* _21 February 2019_ had already been done before
* _February – May 2019_
  * Strangely, I had corrected “quite” → ”quiet” mentally when translating :)
    So VTT and transcript were not updated (nothing to do)
  * Fixed quotes around “Langues” → « Langues » etc. in Translations section
  * Added additionl content in footer

@slhenry or @yatil can you create a fr-translation-update so that I can PR it please?

**Comment by slhenry** [comment]
Thanks, @notabene ! Sorry for my delay in getting back to this.

> Strangely, I had corrected “quite” → ”quiet” mentally when translating :)

I figured probably all translators did this unconsciously-- and probably most readers, too, since no one pointed it out to me. :)

I think there are still a couple minor inconsistencies between the translations in the VTT file and the Transcript table. For example, at the very beginning:
> Bonjour&#8239;! Je m’appelle Shadi Abou-Zahra.
> Bonjour ! Je suis Shadi Abou-Zahra.

I'll send you a comparison file.

**Comment by notabene** [comment]
@slhenry Strange that I overlooked that, really sorry about that. Thanks in advance for the diff file!
